### ISSUE TITLE
Prime X470-PRO BIOS 5603

### ISSUE THREAD

**Issue by ajgringo619** [electrified/asus-wmi-sensors#73]
Has anyone tried this new BIOS update to see if the fan shutdown issue is resolved? I'd really like to use this software, but I can't risk another overheating disaster.

**Comment by KeithMyers** [comment]
Wouldn't it be better to ask this question in a ASUS X470 forum on Overclock.net or Overclockers?

As far as I know the sporadic fan shutdown problem was fixed in several BIOS revisions ago.  Over a year in my recollection.

If you are still worried, just use an external fan control hub and no worries then.

**Comment by ajgringo619** [comment]
I'll do that: thanks. As of revision 5601 (July 2020) this issue still exists.
